# Increment all counters at midnight
- id: increment_filter_counters
  alias: Increment Filter Counters
  trigger:
    - trigger: time
      at: '00:00:00'  # Every day at midnight
  action:
    - action: counter.increment
      target:
        entity_id: counter.water_filter_counter
    - action: counter.increment
      target:
        entity_id: counter.furnace_filter_counter
    - action: counter.increment
      target:
        entity_id: counter.litter_box_litter_counter
    - action: counter.increment
      target:
        entity_id: counter.litter_box_pee_pad_counter

# Update Water Filter Counter when the input number changes
- id: update_water_filter_counter
  alias: Update Water Filter Counter from Input
  trigger:
    - trigger: state
      entity_id: input_number.water_filter_custom_value
  action:
    - action: counter.set_value
      target:
        entity_id: counter.water_filter_counter
      data:
        value: "{{ states('input_number.water_filter_custom_value') | int }}"

# - id: reset_water_filter_days
#   alias: Reset Water Filter Days
#   trigger:
#     - trigger: state
#       entity_id: input_boolean.water_filter_days
#       to: "on"
#   action:
#     - action: input_number.set_value
#       data:
#         entity_id: input_number.water_filter_days
#         value: 0
#     - action: input_boolean.turn_off
#       data:
#         entity_id: input_boolean.water_filter_days
