### Loads default set of integrations. Do not remove. ###
default_config:

frontend:
  themes: !include_dir_merge_named themes

### Text to speech ###
tts:
  - platform: google_translate
    language: "en"

### Yaml file locations ###
sensor: !include sensor.yaml
binary_sensor: !include binary_sensor.yaml
device_tracker: !include device_tracker.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
counter: !include counters.yaml
input_number: !include input_numbers.yaml
input_text: !include input_text.yaml
input_datetime: !include input_datetime.yaml

homeassistant:
  customize: !include customize.yaml
  name: Luv Shack
  latitude:
  longitude:
  elevation: 5330
  unit_system: imperial
  currency: USD
  time_zone: "America/Denver"
  country: US
  
  external_url: "https://<NABU CASA ADDY>"
  internal_url: "http://<HA IP:PORT>"
  #  allowlist_external_dirs:
  #  allowlist_external_urls:
  #    - "http://the-jeffrey.duckdns.org"
  media_dirs:
    media: "/media"
  legacy_templates: false

bluetooth:

template:
  - sensor:
      - name: "Lights On Counter"
        unique_id: lights_on_counter
        state: >-
          {{ states.light | selectattr('state', 'eq', 'on') | list | count | int(0) }}
      - name: "Lights On Entity List"
        unique_id: lights_on_entity_list
        state: >-
          {% set lights_on = states.light | selectattr('state', 'eq', 'on') | map(attribute='entity_id') | list %}
          {{ lights_on | join(',') }}

browser_mod:
  prefix: browser_mod_
  devices:
    # Add device IDs if you want specific device configurations

logger:
  default: info
  logs:
    homeassistant.components.template: debug
