### Mealie ###
- platform: rest
  resource: "http://<MEALIE IP:PORT>/api/groups/mealplans/today"
  method: GET
  name: Mealie todays meal
  headers:
    Authorization: Bearer <Mealie API key>
  value_template: "{{ value_json[0].recipe.name }}"
  force_update: true
  scan_interval: 30

- platform: rest
  resource: "http://<MEALIE IP:PORT>/api/groups/mealplans/today"
  method: GET
  name: Mealie todays meal ID
  headers:
    Authorization: Bearer <Mealie API key>
  value_template: "{{ value_json[0].recipe.id }}"
  force_update: true
  scan_interval: 30
