views:
  - title: Home
    cards:
      - type: custom:mushroom-chips-card
        chips:
          - type: light
            entity: light.bulb_rgbcw_4b036b
            name: Office
          - type: weather
            entity: weather.openweathermap
            show_conditions: true
            show_temperature: true
        alignment: center
      - type: custom:mushroom-template-card
        primary: |-
          {% set time = now().hour %}
          {% if (time >= 18) %}
            Good Evening, {{user}}!
          {% elif (time >= 12) %}
            Good Afternoon, {{user}}!
          {% elif (time >= 5) %}
            Good Morning, {{user}}!
          {% else %}
            Hello, {{user}}!
          {% endif %}
            
        secondary: ''
        icon: ''
      - type: horizontal-stack
        cards:
          - type: custom:mushroom-template-card
            primary: House
            secondary: ''
            icon: mdi:home
            icon_color: blue
            layout: vertical
            tap_action:
              action: navigate
              navigation_path: house
          - type: custom:mushroom-template-card
            primary: Lights
            secondary: ''
            icon: mdi:lightbulb
            icon_color: amber
            layout: vertical
            tap_action:
              action: navigate
              navigation_path: /dashboard-mushroom/lights
          - type: custom:mushroom-template-card
            primary: Secure
            secondary: ''
            icon: mdi:security
            icon_color: green
            layout: vertical
            tap_action:
              action: navigate
              navigation_path: security
          - type: custom:mushroom-template-card
            primary: Net
            secondary: ''
            icon: mdi:network
            icon_color: red
            layout: vertical
            tap_action:
              action: navigate
              navigation_path: /dashboard-mushroom/network
      - type: horizontal-stack
        cards:
          - type: custom:mushroom-person-card
            entity: person.fuller_house
            name: Hefe
            secondary_info: state
            icon_type: entity-picture
            tap_action:
              action: more-info
          - type: custom:mushroom-person-card
            entity: person.skipper
            icon_type: entity-picture
      - type: custom:mushroom-title-card
        title: ''
        subtitle: Devices
      - type: horizontal-stack
        cards:
          - type: custom:mushroom-person-card
            entity: device_tracker.ihefe
            icon: mdi:cellphone-text
            icon_type: icon
            tap_action:
              action: navigate
              navigation_path: ihefe
          - type: custom:mushroom-person-card
            entity: device_tracker.galaxy_tablet
            name: Tablet
            icon: mdi:tablet
            tap_action:
              action: navigate
              navigation_path: tablet
      - type: custom:mushroom-title-card
        title: ''
        subtitle: Rooms
      - type: horizontal-stack
        cards:
          - type: custom:mushroom-template-card
            primary: Office
            secondary: >-
              {{ states('sensor.sonoff_thermometer_temperature_measurement') }}
              °F
            icon: mdi:desk
            entity: light.bulb_rgbcw_4b036b
            tap_action:
              action: navigate
              navigation_path: office
            hold_action:
              action: toggle
            icon_color: |-
              {% if is_state('light.your_light', 'on') %}
                orange
              {% endif %}
          - type: custom:mushroom-template-card
            primary: Master Bed
            secondary: >-
              {{ states('sensor.motion_master_bed_temperature_measurement') }}
              °F
            icon: mdi:bed
            entity: light.bed_lights
            icon_color: |-
              {% if is_state('light.your_light', 'on') %}
                orange
              {% endif %}
            tap_action:
              action: navigate
              navigation_path: master
            hold_action:
              action: toggle
  - title: Office
    path: office
    cards:
      - type: horizontal-stack
        cards:
          - graph: line
            type: sensor
            entity: sensor.sonoff_thermometer_temperature_measurement
            detail: 1
            name: Temperature
          - graph: line
            type: sensor
            entity: sensor.sonoff_thermometer_relative_humidity_measurement
            detail: 1
            name: Humidity
      - type: custom:mushroom-title-card
        title: ''
        subtitle: Devices
      - type: custom:mushroom-light-card
        entity: light.bulb_rgbcw_4b036b
        name: Office Light
        icon: mdi:floor-lamp
        use_light_color: true
        show_brightness_control: true
        show_color_temp_control: true
        show_color_control: true
        collapsible_controls: true
        tap_action:
          action: toggle
    badges:
      - type: custom:mushroom-template-badge
        content: ''
        icon: mdi:arrow-left
        color: red
        tap_action:
          action: navigate
          navigation_path: /tablet-dash
  - title: master
    path: master
    cards:
      - type: horizontal-stack
        cards:
          - graph: line
            type: sensor
            detail: 1
            entity: sensor.motion_master_bed_temperature_measurement
            name: Temperature
          - type: entity
            entity: binary_sensor.motion_master_bed_motion
            name: Motion
      - type: custom:mushroom-light-card
        entity: light.bed_lights
        icon: mdi:led-strip-variant
        use_light_color: true
        show_brightness_control: true
        show_color_temp_control: false
        show_color_control: true
        collapsible_controls: true
        tap_action:
          action: toggle
    badges:
      - type: custom:mushroom-template-badge
        content: ''
        icon: mdi:arrow-left
        color: red
        tap_action:
          action: navigate
          navigation_path: /tablet-dash
  - title: House
    path: house
    icon: mdi:home
    cards:
      - type: horizontal-stack
        cards:
          - graph: line
            type: sensor
            detail: 1
            entity: sensor.ecobee_hub_dining_room_temperature_measurement
            name: Dining Room Temp
            hours_to_show: 48
          - graph: line
            type: sensor
            detail: 1
            entity: sensor.ecobee_hub_dining_room_relative_humidity_measurement
            name: Humidity
      - type: thermostat
        entity: climate.luv_shack
        show_current_as_primary: false
        features:
          - type: climate-fan-modes
            style: dropdown
          - type: climate-hvac-modes
    badges:
      - type: custom:mushroom-template-badge
        content: ''
        icon: mdi:arrow-left
        color: red
        tap_action:
          action: navigate
          navigation_path: /tablet-dash
  - title: Lights
    path: lights
    icon: mdi:lightbulb-group
    cards:
      - type: custom:mushroom-chips-card
        chips:
          - type: back
      - type: horizontal-stack
        cards:
          - type: custom:mushroom-light-card
            entity: light.bulb_rgbcw_4b036b
            name: Office Lamp
            fill_container: true
            use_light_color: true
            show_brightness_control: true
            tap_action:
              action: toggle
            hold_action:
              action: navigate
              navigation_path: /dashboard-mushroom/office
            show_color_control: true
            show_color_temp_control: true
            collapsible_controls: true
      - type: custom:mushroom-light-card
        entity: light.bed_lights
        icon: mdi:led-strip-variant
        use_light_color: true
        show_brightness_control: true
        show_color_temp_control: true
        show_color_control: true
        collapsible_controls: true
        tap_action:
          action: toggle
  - title: Security
    path: security
    icon: mdi:security
    cards:
      - type: custom:mushroom-chips-card
        chips:
          - type: back
  - title: Network
    path: network
    icon: mdi:server-network
    cards:
      - type: custom:mushroom-chips-card
        chips:
          - type: back
      - type: entities
        entities:
          - entity: sensor.fullerfi_udm_uptime
          - entity: sensor.fullerfi_udm_cpu_utilization
          - entity: sensor.fullerfi_udm_memory_utilization
          - entity: update.fullerfi_udm
          - entity: button.fullerfi_udm_restart
        title: UDM Pro
        state_color: true
      - type: vertical-stack
        cards:
          - graph: line
            type: sensor
            entity: sensor.speedtest_download
            detail: 2
            name: Download Speed
            hours_to_show: 48
          - graph: line
            type: sensor
            detail: 2
            entity: sensor.speedtest_upload
            name: Upload Speed
            hours_to_show: 48
          - graph: line
            type: sensor
            entity: sensor.speedtest_ping
            detail: 2
            name: Ping Latency
            hours_to_show: 48
        title: SpeedTest
